# Generated by Django 4.0.5 on 2022-10-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('dui', models.CharField(blank=True, max_length=12, null=True)),
                ('nombre_cliente', models.CharField(max_length=1024)),
                ('direccion', models.CharField(blank=True, max_length=1024, null=True)),
                ('telefono', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idcuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cuenta', models.CharField(max_length=1024)),
                ('tipocuenta', models.CharField(max_length=1024)),
                ('nombre_cuenta', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'cuenta',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('idperiodo', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'periodo',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=1024)),
                ('razon_social', models.CharField(max_length=1024)),
                ('contacto', models.CharField(max_length=8)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('apellido_user', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('passwrd', models.CharField(max_length=1024)),
                ('nombre_user', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Libromayor',
            fields=[
                ('idmayor', models.AutoField(primary_key=True, serialize=False)),
                ('sum_debe', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('sum_haber', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('saldo', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('fecha', models.DateField()),
                ('idperiodo', models.ForeignKey(db_column='idperiodo', on_delete=django.db.models.deletion.DO_NOTHING, to='contable.periodo')),
            ],
            options={
                'db_table': 'libromayor',
            },
        ),
        migrations.CreateModel(
            name='Librodiario',
            fields=[
                ('iddiario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('concepto', models.CharField(max_length=1024)),
                ('cargo', models.BooleanField()),
                ('monto', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('idcuenta', models.ForeignKey(db_column='idcuenta', on_delete=django.db.models.deletion.DO_NOTHING, to='contable.cuenta')),
                ('idmayor', models.ForeignKey(db_column='idmayor', on_delete=django.db.models.deletion.DO_NOTHING, to='contable.libromayor')),
            ],
            options={
                'db_table': 'librodiario',
            },
        ),
    ]
