# Generated by Django 4.0.5 on 2022-10-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libromayor',
            name='saldo',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='sum_debe',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='sum_haber',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
