# Generated by Django 4.0.5 on 2022-10-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0003_alter_librodiario_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromayor',
            name='idcuenta',
            field=models.ForeignKey(db_column='idcuenta', default=int, on_delete=django.db.models.deletion.DO_NOTHING, to='contable.cuenta'),
            preserve_default=False,
        ),
    ]
