# Generated by Django 4.0.5 on 2022-10-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contable', '0004_libromayor_idcuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librodiario',
            name='idmayor',
        ),
        migrations.RemoveField(
            model_name='libromayor',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='libromayor',
            name='idperiodo',
        ),
    ]
